AllCops:
  Exclude:
    - vendor/**

AlignParameters:
  Enabled: false
CyclomaticComplexity:
  Enabled: false
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
NumericLiterals:
  Enabled: false
Style/SpaceBeforeFirstArg:
  Enabled: false
PerceivedComplexity:
  Enabled: false
